import streamlit as st
import datetime
import requests
import sys


Base_URL = "http://localhost:8000"

st.set_page_config(
    page_title="🌎 Travel Planner Agent Application",
    page_icon = "✈️",
    layout="centered",
    initial_sidebar_state="expanded",
)

st.title("🌎 Travel Planner Agent Application")



#initialize chat history 
if "messages" not in st.session_state:
    st.session_state.messages =[]

#Display chat History
st.header("how can i help you in plannig a trip ? Let me know your preferences")

#Chat input box at bottom 
with st.form():
    user_input=st.text_input("User Input ", placeholder="e.g Plan a trip to Goa for 5 days")
    sumbit_button=st.form_submit_button("Send")

if sumbit_button and user_input.strip():
    try:
        ## show user message
        # show thinking spinner while backend processes
        with st.spinner("Deep reserach....."):
            payload = {"question ": user_input}
            response = requests.post(f"{Base_URL}/query",json=payload)

        if response.status_code == 200:
            answer = response.json().get("answer","no answer returned.")
            markdown_content = f"""# 🌎 AI Travel Plan

             ## ** Generated :** {datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")}
             # **Created by:** Atriyo's Travel Agent

            ---

            {answer}

            ---

            *This travel plan was generated by AI. Please verify all information, especially prices, operating hours, and travel requirements before your trip.*
                                                    
"""
            st.markdown(markdown_content)
        else:
            st.error("Bot failed to respond:" + response.text)

    except Exception as e:
        raise f"the response failed due to {e}"
